version: '3.8'

services:
  app:
    container_name: python-app
    build:
      context: .
      dockerfile: ./src/.docker/app/Dockerfile
    tty: true
    volumes:
      - ./src:/app
    ports:
      - 5001:5000
    working_dir: /app
    command: poetry run flask run --host=0.0.0.0
